### ISSUE TITLE
Main menu differs depending on the page

### ISSUE THREAD

**Issue by sylvainraye** [php-etl/documentation#13]
Example from home page:

![Capture d’écran 2021-07-26 à 12 09 04](https://user-images.githubusercontent.com/1337461/126972241-638137a5-3690-42ea-8c03-11b429d0d8b0.png)

Example from https://php-etl.github.io/documentation/components/batch/
![Capture d’écran 2021-07-26 à 12 08 59](https://user-images.githubusercontent.com/1337461/126972281-3fadb3dc-cb0d-4caf-8e59-1c763a462cc8.png)

**Comment by gplanchat** [comment]
Fixed in #16
