### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by programgames** [php-etl/documentation#7]
- [x] add a schematic on the homepage like the one on https://www.akeneo.com/fr/quest-quun-pim/ to explain visually what the middleware can do.
- [x] Improve or change the https://php-etl.github.io/documentation/installation/bare-metal/ to a getting started
- [x] Add a link to https://php-etl.github.io/documentation/components/
- [x] Package/Pipeline is linked to the same page as Component/Satellite
- [x] Update https://php-etl.github.io/documentation/components/satellite/yaml-format/ + explain in details ( example we can use   filesystem or docker configuration)
- [x] Add a schematic for every pages if possible
- [x] https://php-etl.github.io/documentation/components/workflow/ is the same as pipeline
- [x] The YAML configuration format and PHP Objects are barely the same page , normal ? 
- [x] https://php-etl.github.io/documentation/components/satellite/ doc say that the satellite works in the cloud, but we can use it locally, normal ? 
- [x] Fix 404 https://php-etl.github.io/documentation/connectivity/openapi
- [x] #17
- [x] Add a Github action to compile the HTML pages
- [x] Add a summary to each page of documentation
- [x] Add a docker-compose file
- [x] Add the possibility to copy code blocks with a button

**Comment by sebprt** [comment]
Quand tu dis "Add a link to php-etl.github.io/documentation/components", tu veux dire que quand on clique sur "packages" dans le menu, ça redirige dessus ?

Il faut aussi que tu m'expliques ce que tu entends par "Add a JSON Schema for the base application and each plugin"

**Comment by gplanchat** [comment]
> Il faut aussi que tu m'expliques ce que tu entends par "Add a JSON Schema for the base application and each plugin"

JSON schema permet de définir des structures de données et est utilisé par les IDE pour faciliter l'auto-complétion
